from torchvision import models

# "AlexNet","ConvNeXt","DenseNet","EfficientNet","EfficientNetV2","GoogLeNet","Inception V3","MNASNet","MobileNet V2","MobileNet V3","RegNet","ResNet","ResNeXt","ShuffleNet V2","SqueezeNet","SwinTransformer","VGG","VisionTransformer","Wide ResNet"

TORCHVISION_MODEL_MAPPING = {
    "alexnet": models.alexnet,
    "convnext_tiny": models.convnext_tiny,
    "convnext_small": models.convnext_small,
    "convnext_base": models.convnext_base,
    "convnext_large": models.convnext_large,
    "densenet121": models.densenet121,
    "densenet161": models.densenet161,
    "densenet169": models.densenet169,
    "densenet201": models.densenet201,
    "efficientnet_b0": models.efficientnet_b0,
    "efficientnet_b1": models.efficientnet_b1,
    "efficientnet_b2": models.efficientnet_b2,
    "efficientnet_b3": models.efficientnet_b3,
    "efficientnet_b4": models.efficientnet_b4,
    "efficientnet_b5": models.efficientnet_b5,
    "efficientnet_b6": models.efficientnet_b6,
    "efficientnet_b7": models.efficientnet_b7,
    # "efficientnet_v2_s": models.efficientnet_v2_s,
    # "efficientnet_v2_m": models.efficientnet_v2_m,
    # "efficientnet_v2_l": models.efficientnet_v2_l,
    "googlenet": models.googlenet,
    "inception_v3": models.inception_v3,
    "mnasnet0_5": models.mnasnet0_5,
    "mnasnet0_75": models.mnasnet0_75,
    "mnasnet1_0": models.mnasnet1_0,
    "mnasnet1_3": models.mnasnet1_3,
    "mobilenet_v2": models.mobilenet_v2,
    "mobilenet_v3_large": models.mobilenet_v3_large,
    "mobilenet_v3_small": models.mobilenet_v3_small,
    "regnet_y_400mf": models.regnet_y_400mf,
    "regnet_y_800mf": models.regnet_y_800mf,
    "regnet_y_1_6gf": models.regnet_y_1_6gf,
    "regnet_y_3_2gf": models.regnet_y_3_2gf,
    "regnet_y_8gf": models.regnet_y_8gf,
    "regnet_y_16gf": models.regnet_y_16gf,
    "regnet_y_32gf": models.regnet_y_32gf,
    "regnet_y_128gf": models.regnet_y_128gf,
    "regnet_x_400mf": models.regnet_x_400mf,
    "regnet_x_800mf": models.regnet_x_800mf,
    "regnet_x_1_6gf": models.regnet_x_1_6gf,
    "regnet_x_3_2gf": models.regnet_x_3_2gf,
    "regnet_x_8gf": models.regnet_x_8gf,
    "regnet_x_16gf": models.regnet_x_16gf,
    "regnet_x_32gf": models.regnet_x_32gf,
    "resnet18": models.resnet18,
    "resnet34": models.resnet34,
    "resnet50": models.resnet50,
    "resnet101": models.resnet101,
    "resnet152": models.resnet152,
    "resnext50_32x4d": models.resnext50_32x4d,
    "resnext101_32x8d": models.resnext101_32x8d,
    # "resnext101_64x4d": models.resnext101_64x4d,
    "shufflenet_v2_x0_5": models.shufflenet_v2_x0_5,
    "shufflenet_v2_x1_0": models.shufflenet_v2_x1_0,
    "shufflenet_v2_x1_5": models.shufflenet_v2_x1_5,
    "shufflenet_v2_x2_0": models.shufflenet_v2_x2_0,
    "squeezenet1_0": models.squeezenet1_0,
    "squeezenet1_1": models.squeezenet1_1,
    # "swin_t": models.swin_t,
    # "swin_s": models.swin_s,
    # "swin_b": models.swin_b,
    "vgg11": models.vgg11,
    "vgg11_bn": models.vgg11_bn,
    "vgg13": models.vgg13,
    "vgg13_bn": models.vgg13_bn,
    "vgg16": models.vgg16,
    "vgg16_bn": models.vgg16_bn,
    "vgg19": models.vgg19,
    "vgg19_bn": models.vgg19_bn,
    "vit_b_16": models.vit_b_16,
    "vit_b_32": models.vit_b_32,
    "vit_l_16": models.vit_l_16,
    "vit_l_32": models.vit_l_32,
    # "vit_h_14": models.vit_h_14,
    "wide_resnet50_2": models.wide_resnet50_2,
    "wide_resnet101_2": models.wide_resnet101_2
}

